services:
- type: web
  name: Powerhouse-Fitness-Club-Web
  env: python
  repo: https://github.com/MadMoose02/Power-House-Fitness-Club
  plan: free
  branch: master
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: Powerhouse-Fitness-Club-Web-Settings
  - key: POSTGRES_URL
    fromDatabase:
      name: Powerhouse-Fitness-Club-Web-Database
      property: host
  - key: POSTGRES_USER
    fromDatabase:
      name: Powerhouse-Fitness-Club-Web-Database
      property: user
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name: Powerhouse-Fitness-Club-Web-Database
      property: password
  - key: POSTGRES_DB
    fromDatabase:
      name: Powerhouse-Fitness-Club-Web-Database
      property: database

envVarGroups:
- name: Powerhouse-Fitness-Club-Web-Settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py
    
databases:
- name: Powerhouse-Fitness-Club-Web-Database
  plan: free